// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtuxqccanjpqcsfpioac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dXhxY2NhbmpwcWNzZnBpb2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODUyNTQsImV4cCI6MjA2NTU2MTI1NH0.Q46UvqY0Sj_e11Vlj4J5qqJZP9Qo55dc8LJ5h1Z47WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);